version: "3.9"
services:
  db:
    image: postgres:16
    container_name: movieticket-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movieticket
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - movie-net

  backend:
    build: .
    container_name: movieticket-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/movieticket
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=super-secret-jwt-key
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - movie-net

volumes:
  pgdata:

networks:
  movie-net:
    driver: bridge
